  GreenLine = [
    "Lechemere",
    "Science Park",
    "North",
    "Haymarket",
    "Government Center",
    "Park Street",
    "Boylston",
    "Arlington",
    "Copley",
    "Hynes Convention Center",
    "Kenmore",
    "Prudential",
    "Symphony",
    "Northeastern University",
    "Museum of Fine Arts",
    "Longwood Medical Area",
    "Brigham Circle",
    "Fenwood Road",
    "Mission Park",
    "Riverway",
    "Back of the Hill",
    "Heath Street",
    "St. Marry's Street",
    "Haws Street",
    "Kent Street",
    "St. Paul Street",
    "Coolidge Corner",
    "Summit Avenue",
    "Brandon Hall",
    "Fairbanks",
    "Washington Square",
    "Tappan Street",
    "Dean Road",
    "Englewood Avenue",
    "Cleaveland Circle",
    "Blandfod Street",
    "Boston University",
    "Boston University East",
    "Boston University Central",
    "Boston University West",
    "St. Paul St.",
    "Pleasant Street",
    "Babcock Street",
    "Packards Corner",
    "Harvard Avenue",
    "Griggs Street/Long Avenue",
    "Allston Street",
    "Warren Street",
    "Washington Street",
    "Sutherland Road",
    "Chiswick Road",
    "Chestnut Hill Avenue",
    "South Street",
    "Boston College station",
    "Fenway",
    "Longwood",
    "Brookline Village",
    "Brookline Hills",
    "Beaconsfield",
    "Reservior",
    "Chestnut Hill",
    "Newton Centre",
    "Newton Highlands",
    "Eliot",
    "Waban",
    "Woodland",
    "Riverside"
  ];