  OrangeLine = [
  'Oak Grove',
  'Malden Center',
  'Wellington',
  'Assembly',
  'Sullivan Square',
  'Community College',
  'North station',
  'Haymarket',
  'State',
  'Downtown Crossing',
  'Chinatown',
  'Tufts Medical Center',
  'Back Bay',
  'Massachusetts Avenue',
  'Ruggles',
  'Roxbury Crossing',
  'Jackson Square',
  'Stony Brook',
  'Green Street',
  'Forest HIlls'
];